#!/bin/bash
container_self_stop(){
if [ -z "${CRON}" ]; then
  if ! [ -f /opt/backarosa/data/container_volumes.txt ]; then
    container_name=$(cat /proc/self/mountinfo | grep "/docker/containers/" | head -1 | awk '{print $4}' | sed 's/\/var\/lib\/docker\/containers\///g' | sed 's/\/resolv.conf//g')
    docker inspect -f '{{ .Mounts }}' $container_name | grep -oP '(?<={volume )[^ ]*' > /opt/backarosa/data/container_volumes.txt
    container_volumes=( $(cat /opt/backarosa/data/container_volumes.txt) )
  else
    container_volumes=( $(cat /opt/backarosa/data/container_volumes.txt) )   
  fi
    container_close=$(docker ps -a --filter volume=${container_volumes[0]} | grep "backarosa" | awk '{print $1}' | sed 's/CONTAINER//g')
    docker stop $container_close > /dev/null 2>&1
fi
}