#!/bin/bash

source /opt/backarosa/container_self_stop # this is needed to run container_self_stop function

#==========================================================
#======================= MEGA SECTION =====================
#==========================================================
if [ -n "${MEGA_EMAIL}" ] && [ -n "${MEGA_PASSWORD}" ]; then
duplicati-cli restore "mega://${MEGA_DIR}" --auth-username="${MEGA_EMAIL}" --auth-password="${MEGA_PASSWORD}" --no-encryption="true" --restore-permissions="true" --version="${RESTORE_VERSION}"
container_self_stop
fi
#==========================================================
#================== END OF MEGA SECTION ===================
#==========================================================

#==========================================================
# ====================== LOCAL SECTION ====================
#==========================================================
if [ "${LOCAL_BACKUP}" == "true" ]; then
duplicati-cli restore "file://${BACKAROSA_BACKUP}" --no-encryption="true" --restore-permissions="true" --version="${RESTORE_VERSION}"
container_self_stop
fi
#==========================================================
# ================== END OF LOCAL SECTION =================
#==========================================================

#==========================================================
# ====================== GDRIVE SECTION ===================
#==========================================================
if [ -n "${GDRIVE_AUTHID}" ]; then
duplicati-cli restore "googledrive://${GDRIVE_DIR}" --authid="${GDRIVE_AUTHID}" --no-encryption="true" --restore-permissions="true" --version="${RESTORE_VERSION}"
container_self_stop
fi
#==========================================================
# ================== END OF GDRIVE SECTION ================
#==========================================================

#==========================================================
# ====================== DROPBOX SECTION ==================
#==========================================================
if [ -n "${DROPBOX_AUTHID}" ]; then
duplicati-cli restore "dropbox://${DROPBOX_DIR}" --authid="${DROPBOX_AUTHID}" --no-encryption="true" --restore-permissions="true" --version="${RESTORE_VERSION}"
container_self_stop
fi
#==========================================================
# ================== END OF DROPBOX SECTION ==============
#==========================================================
